### ISSUE TITLE
js_facade_gen

### ISSUE THREAD

**Issue by unicomp21** [block-forest/babylonjs-dart-facade#1]
https://github.com/dart-lang/js_facade_gen, what's the difference between dts-converter and js_facade_gen?

**Comment by nilsdoehring** [comment]
dts_converter is a hack-ish way of translating .d.ts via RegEx. I created it as a helper out of personal need when I wanted to have a Dart wrapper for Babylon and THREE. Released it and moved on.

js_facade_gen on the other hand, is cleanly engineered, in that it uses interpreting capabilities of the actual language runtime, has tests, and so on. 

TL;DR: use js_facade_gen

**Comment by unicomp21** [comment]
Have you used js-facade-gen on Babylon?  I'm struggling with it.
